name: Deploy Firebase Backend

on:
  push:
    branches:
      - main  # Runs only when code is merged to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js (Version 22)
        uses: actions/setup-node@v3
        with:
          node-version: 22

      - name: Install Dependencies
        working-directory: backend/functions
        run: npm install

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate Firebase
        run: |
          echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/firebase-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$HOME/firebase-key.json" >> $GITHUB_ENV

      - name: Deploy Firestore Rules & Functions
        working-directory: backend
        run: firebase deploy --only firestore,functions
