name: Deploy Firebase Backend

on:
  push:
    branches:
      - main  # Runs only when code is merged to main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js (Version 21)
        uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Authenticate Firebase
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > firebase-key.json

      - name: Deploy Firestore Rules & Functions
        run: |
          firebase use --add gradient-3b33e
          firebase deploy --only firestore,functions --token "$(cat firebase-key.json)"
